//LOCALHOST GET ALL ROUTES
GET http://localhost:3000/routes
###

// LOCALHOST GET ROUTE BY ID
GET http://localhost:3000/routes/65c5258d38e5687b9384f958
###

// LOCALHOST CREATE ROUTE
POST http://localhost:3000/routes HTTP/1.1
Content-Type: application/json

{
    "name": "TESTING",
    "grade": "5.12",
    "holdColor": "purple",
    "setter": "kevin k",
    "startDate": "",
    "endDate": "",
    "attempts": "14"
}
###

// LOCALHOST UPDATE ROUTE BY ID
PUT http://localhost:3000/routes/65cd27f8de2fb4e146dbfb17 HTTP/1.1
Content-Type: application/json

{
    "name": "Flying Purple People Eater",
    "grade": "5.12",
    "holdColor": "purple",
    "setter": "kevin k",
    "startDate": "1/25/24",
    "endDate": "2/8/24",
    "attempts": "25"
}
###

// LOCALHOST DELETE ROUET BY ID
DELETE http://localhost:3000/routes/65cd27f8de2fb4e146dbfb17
###






//RENDER GET ALL ROUTES
GET https://rockroutes.onrender.com/routes
###

// RENDER GET ROUTE BY ID
GET https://rockroutes.onrender.com/routes/65c53c32a3af6c790142e8ad
###

// RENDER CREATE ROUTE
POST https://rockroutes.onrender.com/routes HTTP/1.1
Content-Type: application/json

{
    "name": "Flying Purple People Eater",
    "grade": "5.12",
    "holdColor": "purple",
    "setter": "kevin k",
    "startDate": "1/25/24",
    "endDate": " ",
    "attempts": "19"
}
###

// RENDER UPDATE ROUTE BY ID
PUT https://rockroutes.onrender.com/routes/65c53c32a3af6c790142e8ad HTTP/1.1
Content-Type: application/json

{
    "name": "Flying Purple People Eater",
    "grade": "5.12",
    "holdColor": "purple",
    "setter": "kevin k",
    "startDate": "1/25/24",
    "endDate": "2/8/24",
    "attempts": "25"
}
###

// RENDER DELETE ROUET BY ID
DELETE https://rockroutes.onrender.com/routes/65c53c32a3af6c790142e8ad
###